regis_webhooks:
    inspections:
        phpcs:
            options: [ '--standard=psr1,psr2' ]
#            enabled: true
#            rules:
#                disallow_short_open_tags: true
        phpmd:
            rulesets: [ 'codesize', 'unusedcode', 'naming', 'controversial', 'design', 'cleancode' ]